#!/bin/bash
# Deepin 25 Repository Source Manager
# Configures APT sources based on selected source profile

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} [sources] $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} [sources] $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} [sources] $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} [sources] $1"; }

# Source profile directory
SOURCES_DIR="${SCRIPT_DIR}/overlays/sources"

# Available source profiles
list_profiles() {
    echo "Available source profiles:"
    echo ""
    echo "  stable           - Community stable repository only (recommended)"
    echo "  testing          - Testing/development repository"
    echo "  hwe              - Hardware Enablement (newer Mesa/drivers)"
    echo "  ports            - ARM/ports optimized repository"
    echo "  stable+testing   - Stable with testing fallback"
    echo "  stable+hwe       - Stable with HWE for new hardware"
    echo "  full             - All repositories (stable+testing+hwe)"
    echo "  custom           - User-provided sources.list"
    echo ""
    echo "Available source files:"
    ls -1 "${SOURCES_DIR}"/*.list 2>/dev/null | sed 's/.*\//    /' | sed 's/.list$//' || echo "  (none found)"
}

# Validate profile
validate_profile() {
    local profile="$1"
    local list_file="${SOURCES_DIR}/${profile}.list"
    
    if [ "$profile" = "custom" ]; then
        if [ -z "$CUSTOM_SOURCES" ] || [ ! -f "$CUSTOM_SOURCES" ]; then
            log_error "Custom profile selected but CUSTOM_SOURCES not set or file not found"
            return 1
        fi
        return 0
    fi
    
    if [ ! -f "$list_file" ]; then
        log_error "Source profile not found: ${list_file}"
        list_profiles
        return 1
    fi
    
    return 0
}

# Setup sources in chroot
setup_sources_chroot() {
    local profile="$1"
    local rootfs="$2"
    
    log_info "Setting up APT sources: ${profile}"
    
    # Determine source file
    if [ "$profile" = "custom" ]; then
        local source_file="$CUSTOM_SOURCES"
    else
        local source_file="${SOURCES_DIR}/${profile}.list"
    fi
    
    # Create sources.list
    cat > "${rootfs}/etc/apt/sources.list" << EOF
# Deepin 25 (Crimson) - Generated by Rockchip Image Builder
# Source Profile: ${profile}
# Build Date: $(date -Iseconds)
#
EOF
    
    # Append selected sources
    cat "$source_file" >> "${rootfs}/etc/apt/sources.list"
    
    # Add priority file if exists
    local pref_file="${SOURCES_DIR}/${profile}-priority.pref"
    if [ -f "$pref_file" ]; then
        log_info "Applying APT priority configuration..."
        mkdir -p "${rootfs}/etc/apt/preferences.d"
        cp "$pref_file" "${rootfs}/etc/apt/preferences.d/10rockchip-builder.pref"
    fi
    
    # Show what was configured
    log_info "sources.list configured:"
    grep "^deb" "${rootfs}/etc/apt/sources.list" | while read line; do
        echo "  ${line}"
    done
    
    log_success "APT sources configured"
}

# Setup sources for build host (mmdebstrap)
setup_sources_build() {
    local profile="$1"
    
    log_info "Build source profile: ${profile}"
    
    # Determine source file
    if [ "$profile" = "custom" ]; then
        local source_file="$CUSTOM_SOURCES"
    else
        local source_file="${SOURCES_DIR}/${profile}.list"
    fi
    
    # Export the primary repo for mmdebstrap
    # mmdebstrap only uses one repo, so we use the stable one
    local primary_repo=$(grep "^deb" "$source_file" | grep "community-packages" | head -1 | sed 's/^deb //')
    
    if [ -z "$primary_repo" ]; then
        primary_repo=$(grep "^deb" "$source_file" | head -1 | sed 's/^deb //')
    fi
    
    echo "$primary_repo"
}

# Update sources in existing chroot (post-install)
update_sources_chroot() {
    local profile="$1"
    local rootfs="$2"
    
    log_info "Updating APT sources in chroot to: ${profile}"
    
    # Remount virtual filesystems if needed
    mount --bind/dev "${rootfs}/dev" 2>/dev/null || true
    mount -t proc chproc "${rootfs}/proc" 2>/dev/null || true
    mount -t sysfs chsys "${rootfs}/sys" 2>/dev/null || true
    
    # Run setup inside chroot
    chroot "$rootfs" /bin/bash -c "
        export DEBIAN_FRONTEND=noninteractive
        
        # Backup original
        cp /etc/apt/sources.list /etc/apt/sources.list.bak.$(date +%s) 2>/dev/null || true
        
        # Update package lists
        apt update -y
        
        echo 'APT sources updated successfully'
    "
    
    log_success "APT sources updated in chroot"
}

# Main
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    case "${1:-}" in
        list)
            list_profiles
            ;;
        validate)
            validate_profile "${2:-}"
            ;;
        *)
            echo "Usage: $0 {list|validate <profile>}"
            exit 1
            ;;
    esac
fi
